# Generated by Django 4.0.3 on 2022-05-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradesApp', '0007_delete_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='semester',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
