# Generated by Django 4.0.3 on 2022-06-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dates', models.CharField(max_length=100)),
                ('times', models.CharField(max_length=100)),
                ('infos', models.CharField(default='null', max_length=500)),
            ],
        ),
    ]
