# Generated by Django 4.0.3 on 2022-05-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='userType',
        ),
    ]
