# Generated by Django 4.0.3 on 2022-05-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_remove_assignment_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='name',
            new_name='title',
        ),
    ]
