# Generated by Django 4.0.3 on 2022-06-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='solution',
        ),
    ]
